"""create contact_info with geography

Revision ID: 080fb4354862
Revises: 94f2bea35d34
Create Date: 2026-07-01 22:49:12.375323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '080fb4354862'
down_revision: Union[str, Sequence[str], None] = '94f2bea35d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('contact_info',
    sa.Column('contact_info_id', sa.UUID(), nullable=False),
    sa.Column('nursing_office_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['nursing_office_id'], ['nursing_office.nursing_office_id'], ),
    sa.PrimaryKeyConstraint('contact_info_id')
    )
    op.create_geospatial_index('idx_contact_info_location', 'contact_info', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_contact_info_nursing_office_id'), 'contact_info', ['nursing_office_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_info_nursing_office_id'), table_name='contact_info')
    op.drop_geospatial_index('idx_contact_info_location', table_name='contact_info', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('contact_info')
    # ### end Alembic commands ###
