"""create conversation and message

Revision ID: 3f60640bc80c
Revises: fffca27eeed1
Create Date: 2026-07-01 23:19:32.489948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3f60640bc80c'
down_revision: Union[str, Sequence[str], None] = 'fffca27eeed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('participant_a', sa.UUID(), nullable=False),
    sa.Column('participant_b', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_a'], ['nurse.user_id'], ),
    sa.ForeignKeyConstraint(['participant_b'], ['nurse.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id'),
    sa.UniqueConstraint('participant_a', 'participant_b', name='uq_conversation_pair')
    )
    op.create_index(op.f('ix_conversation_participant_a'), 'conversation', ['participant_a'], unique=False)
    op.create_index(op.f('ix_conversation_participant_b'), 'conversation', ['participant_b'], unique=False)
    op.create_table('message',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['nurse.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_conversation_participant_b'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_participant_a'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###
