"""create offer table

Revision ID: 44ea59c39706
Revises: e72a1775d61a
Create Date: 2026-07-01 22:01:19.177155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ea59c39706'
down_revision: Union[str, Sequence[str], None] = 'e72a1775d61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('nursing_office_id', sa.UUID(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_turnover', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'EXPIRED', name='offer_status'), nullable=False),
    sa.Column('valid_till', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nursing_office_id'], ['nursing_office.nursing_office_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index(op.f('ix_offer_nursing_office_id'), 'offer', ['nursing_office_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_nursing_office_id'), table_name='offer')
    op.drop_table('offer')
    # ### end Alembic commands ###
