"""create apply table

Revision ID: 94f2bea35d34
Revises: 44ea59c39706
Create Date: 2026-07-01 22:09:05.258403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f2bea35d34'
down_revision: Union[str, Sequence[str], None] = '44ea59c39706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('application_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'REVIEWED', name='application_status'), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='application_decision'), nullable=False),
    sa.Column('decision_comment', sa.String(length=512), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.offer_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['nurse.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'offer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apply')
    # ### end Alembic commands ###
    sa.Enum(name='application_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='application_decision').drop(op.get_bind(), checkfirst=True)
