"""add two factor fields to users

Revision ID: a65f3a92aa72
Revises: c5c4b6c5e9eb
Create Date: 2026-07-03 22:32:48.626462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a65f3a92aa72'
down_revision: Union[str, Sequence[str], None] = 'c5c4b6c5e9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'two_factor_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'two_factor_enabled')
    # ### end Alembic commands ###
