"""create nursing_office and belong

Revision ID: e72a1775d61a
Revises: 2dd400577081
Create Date: 2026-07-01 21:53:53.641399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72a1775d61a'
down_revision: Union[str, Sequence[str], None] = '2dd400577081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nursing_office',
    sa.Column('nursing_office_id', sa.UUID(), nullable=False),
    sa.Column('nursing_office_name', sa.String(length=255), nullable=False),
    sa.Column('siret', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='nursing_office_status'), nullable=False),
    sa.PrimaryKeyConstraint('nursing_office_id')
    )
    op.create_table('belong',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nursing_office_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['nursing_office_id'], ['nursing_office.nursing_office_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['nurse.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'nursing_office_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('belong')
    op.drop_table('nursing_office')
    # ### end Alembic commands ###
    sa.Enum(name='nursing_office_status').drop(op.get_bind(), checkfirst=True)
