"""create care and offer_care

Revision ID: fffca27eeed1
Revises: 080fb4354862
Create Date: 2026-07-01 23:03:44.914362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'fffca27eeed1'
down_revision: Union[str, Sequence[str], None] = '080fb4354862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care',
    sa.Column('care_id', sa.UUID(), nullable=False),
    sa.Column('care_name', sa.String(length=255), nullable=False),
    sa.Column('cotation_ngap', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prescription_necessary', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('care_id')
    )
    op.create_index(op.f('ix_care_care_name'), 'care', ['care_name'], unique=True)
    op.create_table('offer_care',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('care_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['care_id'], ['care.care_id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.offer_id'], ),
    sa.PrimaryKeyConstraint('offer_id', 'care_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_care')
    op.drop_index(op.f('ix_care_care_name'), table_name='care')
    op.drop_table('care')
    # ### end Alembic commands ###
